#!/usr/bin/env bash
# Build Mission Control and deploy to Butterbase frontend hosting.
#
# Prerequisites:
#   - BUTTERBASE_APP_ID + BUTTERBASE_API_KEY in root .env (dashboard API key)
#   - VITE_SENSOR_URL + VITE_RESPONDER_URL — public URLs where sensor (:3003) and
#     responder (:3004) are reachable (VPS, ngrok, Cloudflare tunnel, etc.)
#   - sensor/responder must allow CORS (CORS_ORIGIN=* by default)
#
# Usage:
#   ./scripts/deploy-frontend.sh
#   VITE_SENSOR_URL=https://… VITE_RESPONDER_URL=https://… ./scripts/deploy-frontend.sh
#   ./scripts/deploy-frontend.sh --shell-only   # UI + Butterbase auth only (no live engine)
set -euo pipefail

SHELL_ONLY=0
if [[ "${1:-}" == "--shell-only" ]]; then
  SHELL_ONLY=1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FRONTEND="$ROOT/frontend"
DIST_ZIP="$FRONTEND/dist.zip"

if [[ ! -f "$ROOT/.env" ]]; then
  echo "Missing $ROOT/.env — copy .env.example and fill in API keys."
  exit 1
fi

set -a
# shellcheck disable=SC1091
source "$ROOT/.env"
set +a

APP_ID="${BUTTERBASE_APP_ID:-${VITE_BUTTERBASE_APP_ID:-}}"
API_URL="${BUTTERBASE_API_URL:-https://api.butterbase.ai}"
API_KEY="${BUTTERBASE_API_KEY:-}"
SENSOR_URL="${VITE_SENSOR_URL:-${DEPLOY_SENSOR_URL:-}}"
RESPONDER_URL="${VITE_RESPONDER_URL:-${DEPLOY_RESPONDER_URL:-}}"

if [[ -z "$APP_ID" ]]; then
  echo "Set BUTTERBASE_APP_ID in .env"
  exit 1
fi
if [[ -z "$API_KEY" ]]; then
  echo "Set BUTTERBASE_API_KEY in .env (dashboard API key with deploy scope)"
  exit 1
fi
if [[ "$SHELL_ONLY" -eq 0 && ( -z "$SENSOR_URL" || -z "$RESPONDER_URL" ) ]]; then
  echo "Set public backend URLs before deploying (the hosted UI cannot reach localhost):"
  echo "  VITE_SENSOR_URL=https://your-host:3003"
  echo "  VITE_RESPONDER_URL=https://your-host:3004"
  echo ""
  echo "Or deploy the UI shell only (Butterbase auth + panels; engine stays local):"
  echo "  ./scripts/deploy-frontend.sh --shell-only"
  echo ""
  echo "Tip: expose your laptop with ngrok (authtoken required) or run on a VPS."
  exit 1
fi

# Strip trailing slashes — fetch() concatenates paths.
SENSOR_URL="${SENSOR_URL%/}"
RESPONDER_URL="${RESPONDER_URL%/}"

echo "=== production env for Vite build ==="
if [[ "$SHELL_ONLY" -eq 1 ]]; then
  echo "  mode: shell-only (no public sensor/responder — run engine locally for live demo)"
  cat >"$FRONTEND/.env.production" <<EOF
# Generated by scripts/deploy-frontend.sh --shell-only
VITE_NEO4J_URL=${NEO4J_URL:-${NEO4J_URI:-}}
VITE_NEO4J_USER=${NEO4J_USER:-${NEO4J_USERNAME:-neo4j}}
VITE_NEO4J_PASSWORD=${NEO4J_PASSWORD:-}
VITE_BUTTERBASE_APP_ID=$APP_ID
VITE_BUTTERBASE_API_URL=${API_URL}
VITE_AUTO_LOGIN=${VITE_AUTO_LOGIN:-1}
VITE_DEMO_EMAIL=${VITE_DEMO_EMAIL:-oncall@rescueops.dev}
VITE_DEMO_PASSWORD=${VITE_DEMO_PASSWORD:-Resc!ue0ps2026}
EOF
else
  cat >"$FRONTEND/.env.production" <<EOF
# Generated by scripts/deploy-frontend.sh — do not commit
VITE_SENSOR_URL=$SENSOR_URL
VITE_RESPONDER_URL=$RESPONDER_URL
VITE_NEO4J_URL=${NEO4J_URL:-${NEO4J_URI:-}}
VITE_NEO4J_USER=${NEO4J_USER:-${NEO4J_USERNAME:-neo4j}}
VITE_NEO4J_PASSWORD=${NEO4J_PASSWORD:-}
VITE_BUTTERBASE_APP_ID=$APP_ID
VITE_BUTTERBASE_API_URL=${API_URL}
VITE_AUTO_LOGIN=${VITE_AUTO_LOGIN:-1}
VITE_DEMO_EMAIL=${VITE_DEMO_EMAIL:-oncall@rescueops.dev}
VITE_DEMO_PASSWORD=${VITE_DEMO_PASSWORD:-Resc!ue0ps2026}
EOF
  echo "  sensor   → $SENSOR_URL"
  echo "  responder→ $RESPONDER_URL"
fi
echo "  app      → $APP_ID"

echo "=== npm run build ==="
if [[ ! -d "$FRONTEND/node_modules" ]]; then
  npm install --prefix "$FRONTEND"
fi
npm run build --prefix "$FRONTEND"

echo "=== zip dist/ ==="
rm -f "$DIST_ZIP"
(cd "$FRONTEND/dist" && zip -qr "$DIST_ZIP" .)

echo "=== create Butterbase deployment ==="
CREATE_JSON=$(curl -sf -X POST "$API_URL/v1/$APP_ID/frontend/deployments" \
  -H "Authorization: Bearer $API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"framework":"react-vite"}')

DEPLOY_ID=$(echo "$CREATE_JSON" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const j=JSON.parse(s);process.stdout.write(j.id||"")})')
UPLOAD_URL=$(echo "$CREATE_JSON" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const j=JSON.parse(s);process.stdout.write(j.uploadUrl||"")})')

if [[ -z "$DEPLOY_ID" || -z "$UPLOAD_URL" ]]; then
  echo "create deployment failed: $CREATE_JSON"
  exit 1
fi
echo "  deployment id: $DEPLOY_ID"

echo "=== upload zip ==="
curl -sf -X PUT "$UPLOAD_URL" \
  -H "Content-Type: application/zip" \
  --data-binary @"$DIST_ZIP"

echo "=== start deployment ==="
curl -sf -X POST "$API_URL/v1/$APP_ID/frontend/deployments/$DEPLOY_ID/start" \
  -H "Authorization: Bearer $API_KEY"

echo "=== waiting for READY ==="
LIVE_URL=""
for _ in $(seq 1 60); do
  DETAIL=$(curl -sf "$API_URL/v1/$APP_ID/frontend/deployments/$DEPLOY_ID" \
    -H "Authorization: Bearer $API_KEY")
  STATUS=$(echo "$DETAIL" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const j=JSON.parse(s);process.stdout.write(j.status||j.deployment?.status||"")})')
  LIVE_URL=$(echo "$DETAIL" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const j=JSON.parse(s);const u=j.url||j.liveUrl||j.deployment?.url||j.deployment?.liveUrl||"";process.stdout.write(u)})')
  echo "  status: $STATUS"
  if [[ "$STATUS" == "READY" ]]; then
    break
  fi
  if [[ "$STATUS" == "ERROR" || "$STATUS" == "CANCELED" ]]; then
    echo "deployment failed: $DETAIL"
    exit 1
  fi
  sleep 5
done

rm -f "$DIST_ZIP"

if [[ -z "$LIVE_URL" ]]; then
  echo ""
  echo "Deployment started. Check the Butterbase dashboard → Deployments for the live URL."
  echo "https://dashboard.butterbase.ai/apps/$APP_ID/deployments"
else
  echo ""
  echo "Mission Control live → $LIVE_URL"
fi
