#!/usr/bin/env bash
# Run sensor, responder, and frontend on the host — no Docker required.
# Neo4j: uses Aura credentials from .env (NEO4J_URI / NEO4J_USERNAME / …).
#
# Usage:
#   ./scripts/dev-native.sh          # start all services
#   ./scripts/dev-native.sh stop     # stop background services
#   ./scripts/dev-native.sh status   # show what's running
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PID_DIR="$ROOT/.dev"
SENSOR_PID="$PID_DIR/sensor.pid"
RESPONDER_PID="$PID_DIR/responder.pid"
FRONTEND_PID="$PID_DIR/frontend.pid"
SENSOR_LOG="$PID_DIR/sensor.log"
RESPONDER_LOG="$PID_DIR/responder.log"
FRONTEND_LOG="$PID_DIR/frontend.log"
TARGET="$ROOT/target-repo"
FRONTEND_ENV="$ROOT/frontend/.env.local"

port_owner() {
  lsof -nP -iTCP:"$1" -sTCP:LISTEN 2>/dev/null | awk 'NR==2 {print $1, $2}'
}

stop_pid() {
  local file=$1
  if [[ -f "$file" ]]; then
    local pid
    pid=$(cat "$file")
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
    fi
    rm -f "$file"
  fi
}

stop_all() {
  stop_pid "$FRONTEND_PID"
  stop_pid "$RESPONDER_PID"
  stop_pid "$SENSOR_PID"
  echo "Stopped native dev services."
}

status_all() {
  echo "=== ports ==="
  for port in 3003 3004 5173; do
    owner=$(port_owner "$port" || true)
    echo "  :$port  ${owner:-free}"
  done
  echo "=== native pids ==="
  for entry in "sensor:$SENSOR_PID" "responder:$RESPONDER_PID" "frontend:$FRONTEND_PID"; do
    label=${entry%%:*}
    file=${entry#*:}
    if [[ -f "$file" ]] && kill -0 "$(cat "$file")" 2>/dev/null; then
      echo "  $label  running (pid $(cat "$file"))"
    else
      echo "  $label  stopped"
    fi
  done
  echo "=== logs ==="
  echo "  $SENSOR_LOG"
  echo "  $RESPONDER_LOG"
  echo "  $FRONTEND_LOG"
}

ensure_env() {
  if [[ ! -f "$ROOT/.env" ]]; then
    echo "Missing $ROOT/.env — copy .env.example and fill in API keys."
    exit 1
  fi
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a

  if [[ -z "${NEO4J_URI:-}" && -z "${NEO4J_URL:-}" ]]; then
    echo "Set NEO4J_URI in .env (Aura) or NEO4J_URL=bolt://localhost:7687 for a local Neo4j."
    exit 1
  fi

  export TARGET_DIR="$TARGET"
  export SENSOR_URL="${SENSOR_URL:-http://localhost:3003}"
  export PORT
}

ensure_ports_free() {
  local blocked=0
  for port in 3003 3004; do
    owner=$(port_owner "$port" || true)
    if [[ -n "$owner" ]]; then
      echo "Port $port is in use by: $owner"
      if [[ "$owner" == com.docke* ]]; then
        echo "  → Stop Docker backends: docker stop \$(docker ps -q --filter publish=$port) 2>/dev/null || true"
      fi
      blocked=1
    fi
  done
  if [[ "$blocked" -eq 1 ]]; then
    echo "Free ports 3003 and 3004, then re-run ./scripts/dev-native.sh"
    exit 1
  fi
}

sync_frontend_env() {
  # Vite only reads VITE_* from frontend/.env.local
  cat >"$FRONTEND_ENV" <<EOF
# Auto-generated by scripts/dev-native.sh — do not commit (gitignored)
VITE_NEO4J_URL=${NEO4J_URL:-${NEO4J_URI}}
VITE_NEO4J_USER=${NEO4J_USER:-${NEO4J_USERNAME:-neo4j}}
VITE_NEO4J_PASSWORD=${NEO4J_PASSWORD}
VITE_BUTTERBASE_APP_ID=${BUTTERBASE_APP_ID:-app_gsuwgmmbc74g}
VITE_BUTTERBASE_API_URL=${BUTTERBASE_API_URL:-https://api.butterbase.ai}
EOF
}

install_if_needed() {
  local dir=$1
  if [[ ! -d "$dir/node_modules" ]]; then
    echo "Installing $dir…"
    npm install --prefix "$dir"
  fi
}

start_bg() {
  local name=$1 pidfile=$2 logfile=$3 workdir=$4 port=$5
  mkdir -p "$PID_DIR"
  # nohup so sensor/responder survive when this script's shell exits (e.g. CI/agents).
  nohup bash -c "
    cd $(printf '%q' "$workdir")
    set -a
    source $(printf '%q' "$ROOT/.env")
    set +a
    export TARGET_DIR=$(printf '%q' "$TARGET")
    export SENSOR_URL=${SENSOR_URL:-http://localhost:3003}
    export PORT=$port
    exec npm start
  " >"$logfile" 2>&1 &
  echo $! >"$pidfile"
  disown "$(cat "$pidfile")" 2>/dev/null || true
  echo "Started $name on :$port (pid $(cat "$pidfile"), log $logfile)"
}

wait_for() {
  local url=$1 label=$2
  for _ in $(seq 1 30); do
    if curl -sf "$url" >/dev/null 2>&1; then
      echo "$label ready"
      return 0
    fi
    sleep 1
  done
  echo "$label did not become ready — check logs in $PID_DIR/"
  return 1
}

start_all() {
  ensure_env
  ensure_ports_free
  mkdir -p "$PID_DIR"
  sync_frontend_env

  if [[ ! -d "$TARGET" ]]; then
    echo "Missing $TARGET — create or clone the patient repo there first."
    exit 1
  fi

  install_if_needed "$ROOT/services/sensor"
  install_if_needed "$ROOT/services/responder"
  install_if_needed "$ROOT/frontend"
  install_if_needed "$TARGET"

  stop_all 2>/dev/null || true

  echo "Neo4j → ${NEO4J_URL:-${NEO4J_URI}} (database: ${NEO4J_DATABASE:-default})"

  start_bg sensor "$SENSOR_PID" "$SENSOR_LOG" "$ROOT/services/sensor" 3003

  wait_for "http://localhost:3003/incident" "sensor"

  start_bg responder "$RESPONDER_PID" "$RESPONDER_LOG" "$ROOT/services/responder" 3004

  wait_for "http://localhost:3004/connection" "responder"

  owner=$(port_owner 5173 || true)
  if [[ -n "$owner" ]]; then
    echo "Frontend already listening on :5173 ($owner) — leaving it running."
  else
    (
      cd "$ROOT/frontend"
      exec npm run dev -- --host 127.0.0.1 --port 5173
    ) >"$FRONTEND_LOG" 2>&1 &
    echo $! >"$FRONTEND_PID"
    disown "$(cat "$FRONTEND_PID")" 2>/dev/null || true
    echo "Started frontend on :5173 (pid $(cat "$FRONTEND_PID"), log $FRONTEND_LOG)"
    sleep 2
  fi

  echo ""
  echo "Mission Control → http://localhost:5173"
  echo "Sensor          → http://localhost:3003/incident"
  echo "Responder       → http://localhost:3004/connection"
  echo "Neo4j shell     → ./scripts/cypher-shell.sh"
  echo ""
  echo "Seed incident   → ./scripts/break.sh"
  echo "Stop everything → ./scripts/dev-native.sh stop"
  echo "Logs            → tail -f $PID_DIR/*.log"
}

case "${1:-start}" in
  stop) stop_all ;;
  status) status_all ;;
  start|"") start_all ;;
  *)
    echo "Usage: $0 [start|stop|status]"
    exit 1
    ;;
esac
