#!/usr/bin/env bash
# Run sensor, responder, and frontend on the host — no Docker required.
# Neo4j: uses Aura credentials from .env (NEO4J_URI / NEO4J_USERNAME / …).
#
# Usage:
#   ./scripts/dev-native.sh          # start all services
#   ./scripts/dev-native.sh stop     # stop background services
#   ./scripts/dev-native.sh status   # show what's running
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PID_DIR="$ROOT/.dev"
SENSOR_PID="$PID_DIR/sensor.pid"
RESPONDER_PID="$PID_DIR/responder.pid"
FRONTEND_PID="$PID_DIR/frontend.pid"
SENSOR_LOG="$PID_DIR/sensor.log"
RESPONDER_LOG="$PID_DIR/responder.log"
FRONTEND_LOG="$PID_DIR/frontend.log"
TARGET="${PATIENT_REPO:-$ROOT/target-repo}"
# Resolve a relative PATIENT_REPO (e.g. patients/claimflow) against the repo
# root — the services run from their own cwd and would otherwise miss it.
case "$TARGET" in
  /*) ;;
  *) TARGET="$ROOT/$TARGET" ;;
esac
FRONTEND_ENV="$ROOT/frontend/.env.local"

port_owner() {
  lsof -nP -iTCP:"$1" -sTCP:LISTEN 2>/dev/null | awk 'NR==2 {print $1, $2}'
}

stop_pid() {
  local file=$1
  if [[ -f "$file" ]]; then
    local pid
    pid=$(cat "$file")
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
    fi
    rm -f "$file"
  fi
}

stop_all() {
  stop_pid "$FRONTEND_PID"
  stop_pid "$RESPONDER_PID"
  stop_pid "$SENSOR_PID"
  # The pidfiles hold the launcher pids; npm's node children can survive them.
  # Sweep the service ports so a restart never races a half-dead process.
  for port in 3003 3004 5173; do
    lsof -nP -iTCP:"$port" -sTCP:LISTEN 2>/dev/null | awk 'NR>1 {print $2}' | sort -u | while read -r pid; do
      kill "$pid" 2>/dev/null || true
    done
  done
  echo "Stopped native dev services."
}

status_all() {
  echo "=== ports ==="
  for port in 3003 3004 5173; do
    owner=$(port_owner "$port" || true)
    echo "  :$port  ${owner:-free}"
  done
  echo "=== native pids ==="
  for entry in "sensor:$SENSOR_PID" "responder:$RESPONDER_PID" "frontend:$FRONTEND_PID"; do
    label=${entry%%:*}
    file=${entry#*:}
    if [[ -f "$file" ]] && kill -0 "$(cat "$file")" 2>/dev/null; then
      echo "  $label  running (pid $(cat "$file"))"
    else
      echo "  $label  stopped"
    fi
  done
  echo "=== logs ==="
  echo "  $SENSOR_LOG"
  echo "  $RESPONDER_LOG"
  echo "  $FRONTEND_LOG"
}

ensure_env() {
  if [[ ! -f "$ROOT/.env" ]]; then
    echo "Missing $ROOT/.env — copy .env.example and fill in API keys."
    exit 1
  fi
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a

  if [[ -z "${NEO4J_URI:-}" && -z "${NEO4J_URL:-}" ]]; then
    echo "Set NEO4J_URI in .env (Aura) or NEO4J_URL=bolt://localhost:7687 for a local Neo4j."
    exit 1
  fi

  export TARGET_DIR="$TARGET"
  export PATIENT_REPO="${PATIENT_REPO:-target-repo}"
  export SENSOR_URL="${SENSOR_URL:-http://localhost:3003}"
  export PORT
}

ensure_ports_free() {
  local blocked=0
  for port in 3003 3004; do
    owner=$(port_owner "$port" || true)
    if [[ -n "$owner" ]]; then
      echo "Port $port is in use by: $owner"
      if [[ "$owner" == com.docke* ]]; then
        echo "  → Stop Docker backends: docker stop \$(docker ps -q --filter publish=$port) 2>/dev/null || true"
      fi
      blocked=1
    fi
  done
  if [[ "$blocked" -eq 1 ]]; then
    echo "Free ports 3003 and 3004, then re-run ./scripts/dev-native.sh"
    exit 1
  fi
}

sync_frontend_env() {
  # Vite only reads VITE_* from frontend/.env.local
  cat >"$FRONTEND_ENV" <<EOF
# Auto-generated by scripts/dev-native.sh — do not commit (gitignored)
VITE_NEO4J_URL=${NEO4J_URL:-${NEO4J_URI}}
VITE_NEO4J_USER=${NEO4J_USER:-${NEO4J_USERNAME:-neo4j}}
VITE_NEO4J_PASSWORD=${NEO4J_PASSWORD}
VITE_BUTTERBASE_APP_ID=${BUTTERBASE_APP_ID:-app_gsuwgmmbc74g}
VITE_BUTTERBASE_API_URL=${BUTTERBASE_API_URL:-https://api.butterbase.ai}
VITE_AUTO_LOGIN=1
VITE_DEMO_EMAIL=oncall@rescueops.dev
VITE_DEMO_PASSWORD=Resc!ue0ps2026
EOF
}

install_if_needed() {
  local dir=$1
  if [[ ! -d "$dir/node_modules" ]]; then
    echo "Installing $dir ..."
    npm install --prefix "$dir"
  fi
}

start_bg() {
  local name=$1 pidfile=$2 logfile=$3 workdir=$4 port=$5
  local launcher="$PID_DIR/launch-$name.sh"
  mkdir -p "$PID_DIR"
  cat >"$launcher" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd $(printf '%q' "$workdir")
set -a
source $(printf '%q' "$ROOT/.env")
set +a
export TARGET_DIR=$(printf '%q' "$TARGET")
export SENSOR_URL=${SENSOR_URL:-http://localhost:3003}
export PORT=$port
exec npm start
EOF
  chmod +x "$launcher"
  : >"$logfile"
  nohup "$launcher" >>"$logfile" 2>&1 < /dev/null &
  echo $! >"$pidfile"
  disown "$(cat "$pidfile")" 2>/dev/null || true
  echo "Started $name on :$port (pid $(cat "$pidfile"), log $logfile)"
}

wait_for() {
  local url=$1 label=$2
  for _ in $(seq 1 30); do
    if curl -sf "$url" >/dev/null 2>&1; then
      echo "$label ready"
      return 0
    fi
    sleep 1
  done
  echo "$label did not become ready — check logs in $PID_DIR/"
  return 1
}

start_all() {
  ensure_env
  ensure_ports_free
  mkdir -p "$PID_DIR"
  sync_frontend_env

  if [[ ! -d "$TARGET" ]]; then
    echo "Missing $TARGET — create or clone the patient repo there first."
    exit 1
  fi

  install_if_needed "$ROOT/services/sensor"
  install_if_needed "$ROOT/services/responder"
  install_if_needed "$ROOT/frontend"
  install_if_needed "$TARGET"

  stop_all 2>/dev/null || true

  echo "Neo4j → ${NEO4J_URL:-${NEO4J_URI}} (database: ${NEO4J_DATABASE:-default})"

  start_bg sensor "$SENSOR_PID" "$SENSOR_LOG" "$ROOT/services/sensor" 3003

  wait_for "http://localhost:3003/incident" "sensor"

  start_bg responder "$RESPONDER_PID" "$RESPONDER_LOG" "$ROOT/services/responder" 3004

  wait_for "http://localhost:3004/connection" "responder"

  owner=$(port_owner 5173 || true)
  if [[ -n "$owner" ]]; then
    echo "Frontend already listening on :5173 ($owner) — leaving it running."
  else
    local flauncher="$PID_DIR/launch-frontend.sh"
    cat >"$flauncher" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd $(printf '%q' "$ROOT/frontend")
exec npm run dev -- --host 0.0.0.0 --port 5173
EOF
    chmod +x "$flauncher"
    : >"$FRONTEND_LOG"
    nohup "$flauncher" >>"$FRONTEND_LOG" 2>&1 < /dev/null &
    echo $! >"$FRONTEND_PID"
    disown "$(cat "$FRONTEND_PID")" 2>/dev/null || true
    echo "Started frontend on :5173 (pid $(cat "$FRONTEND_PID"), log $FRONTEND_LOG)"
    sleep 2
  fi

  echo ""
  echo "Mission Control → http://127.0.0.1:5173"
  echo "  (use 127.0.0.1 — http://localhost:5173 can fail on IPv6)"
  echo "Sensor          → http://127.0.0.1:3003/incident"
  echo "Responder       → http://127.0.0.1:3004/connection"
  echo "Neo4j shell     → ./scripts/cypher-shell.sh"
  echo ""
  echo "Seed incident   → ./scripts/break.sh"
  echo "Stop everything → ./scripts/dev-native.sh stop"
  echo "Logs            → tail -f $PID_DIR/*.log"
  if [[ "$(uname -s)" == "Darwin" ]]; then
    open "http://127.0.0.1:5173" 2>/dev/null || true
  fi

  # Keep this terminal session alive so services are not orphaned/killed.
  if [[ -t 1 ]]; then
    echo ""
    echo "Services running — leave this tab open (Ctrl+C to stop)."
    trap 'stop_all; exit 0' INT TERM
    while true; do
      for f in "$SENSOR_PID" "$RESPONDER_PID" "$FRONTEND_PID"; do
        if [[ -f "$f" ]] && ! kill -0 "$(cat "$f")" 2>/dev/null; then
          echo "A service exited unexpectedly — check logs in $PID_DIR/"
          stop_all
          exit 1
        fi
      done
      sleep 3
    done
  fi
}

case "${1:-start}" in
  stop) stop_all ;;
  status) status_all ;;
  start|"") start_all ;;
  *)
    echo "Usage: $0 [start|stop|status]"
    exit 1
    ;;
esac
